# devops/sonarqube/sonar-project.properties

sonar.organization=UvereAnn_national_vehicle_registry
sonar.projectKey=uvereann

sonar.sources=.
# All exclusions combined cleanly into one line
sonar.exclusions=**/node_modules/**,**/dist/**,**/venv/**,devops/**,database/**,.github/workflows/**

sonar.sourceEncoding=UTF-8