# devops/sonarqube/sonar-project.properties

sonar.organization=UvereAnn_national_vehicle_registry
sonar.projectKey=UvereAnn_national_vehicle_registry

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/venv/**,devops/**,database/**

sonar.sourceEncoding=UTF-8