sonar.projectKey=NVR
sonar.projectName=National Vehicle Registry
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/venv/**,**/*.test.js,**/dist/**,devops/**
sonar.sourceEncoding=UTF-8
