apiVersion: v1
kind: ConfigMap
metadata:
  name: nvr-config
  namespace: nvr-production
data:
  # ⚠️ Replace with your PRODUCTION RDS endpoint from terraform output
  DB_HOST: "nvr-mysql-production.cxu48ymoqdks.eu-north-1.rds.amazonaws.com"
  DB_NAME: "nvr_db"
  DB_USER: "admin"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  VEHICLE_SERVICE_URL: "http://vehicle-service:3002"
  PLATE_SERVICE_URL: "http://plate-service:3003"
  FRONTEND_URL: "https://nvr.yourdomain.com"
  NODE_ENV: "production"
