apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvr-production
  namespace: argocd
  labels:
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/UvereAnn/national_vehicle_registry
    targetRevision: main
    path: devops/kubernetes/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: nvr-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: false   # Do NOT auto-fix in production — require manual review
    syncOptions:
    - CreateNamespace=true
